### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jiuexika** [haoyuhu/dify-client-python#2]
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by haoyuhu** [comment]
I think the following PR fixes this.
https://github.com/haoyuhu/dify-client-python/pull/1#issuecomment-2140625116
Please wait for me to release a fix version.

**Comment by haoyuhu** [comment]
Please try the latest v1.0.1 version, which fixes this.
Thanks to @qbit-
